# Generated by Django 5.0.4 on 2024-04-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0002_appuser_delete_user'),
        ('pes', '0003_rename_register_user'),
    ]

    operations = [
    ]
