# Generated by Django 5.0.4 on 2024-04-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0005_remove_user_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otpCode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
