# Generated by Django 5.0.4 on 2024-05-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0006_user_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesEvents',
            fields=[
                ('eventID', models.BigAutoField(primary_key=True, serialize=False)),
                ('OLDdID', models.IntegerField(null=True)),
                ('FSPID', models.IntegerField()),
                ('eventdate', models.DateTimeField(null=True)),
                ('d_First', models.CharField(max_length=75)),
                ('d_middle_a', models.CharField(max_length=75, null=True)),
                ('d_middle_b', models.CharField(max_length=75, null=True)),
                ('d_Last', models.CharField(max_length=125)),
                ('d_Maiden', models.CharField(max_length=125, null=True)),
                ('d_Address', models.CharField(max_length=255)),
                ('d_Unit', models.CharField(max_length=50, null=True)),
                ('d_City', models.CharField(max_length=125)),
                ('d_Prov', models.CharField(max_length=3)),
                ('d_Postal', models.CharField(max_length=12)),
                ('d_AreaCode', models.IntegerField(null=True)),
                ('d_exchange', models.IntegerField(null=True)),
                ('d_phone', models.CharField(max_length=4, null=True)),
                ('d_DOB', models.DateTimeField()),
                ('d_birth_Country', models.CharField(max_length=125)),
                ('d_birth_City', models.CharField(max_length=125, null=True)),
                ('d_birth_Prov', models.CharField(max_length=3, null=True)),
                ('d_DOD', models.DateTimeField()),
                ('d_death_Country', models.CharField(max_length=125)),
                ('d_death_City', models.CharField(max_length=125, null=True)),
                ('d_death_Prov', models.CharField(max_length=3, null=True)),
                ('d_SIN', models.CharField(max_length=11, null=True)),
                ('d_PHC', models.CharField(max_length=50, null=True)),
                ('d_Prov_PHC', models.CharField(max_length=3, null=True)),
                ('d_BCN', models.CharField(max_length=255, null=True)),
                ('d_death_age', models.IntegerField()),
                ('d_disp_Name', models.CharField(max_length=275)),
                ('d_disp_Postal', models.CharField(max_length=12)),
                ('d_dispdate', models.DateTimeField()),
                ('e_Salutation', models.CharField(max_length=12, null=True)),
                ('e_First', models.CharField(max_length=75)),
                ('e_Initial', models.CharField(max_length=75, null=True)),
                ('e_Last', models.CharField(max_length=125)),
                ('e_Address', models.CharField(max_length=255)),
                ('e_Unit', models.CharField(max_length=50, null=True)),
                ('e_City', models.CharField(max_length=125)),
                ('e_Prov', models.CharField(max_length=3)),
                ('e_Postal', models.CharField(max_length=12)),
                ('e_AreaCode', models.IntegerField(null=True)),
                ('e_exchange', models.IntegerField(null=True)),
                ('e_phone_4', models.CharField(max_length=4)),
                ('e_relationship', models.CharField(max_length=50)),
                ('ExecutorID', models.IntegerField(null=True)),
                ('FaxDate', models.DateTimeField(null=True)),
                ('ReportDate', models.DateTimeField(null=True)),
                ('Status', models.CharField(max_length=50, null=True)),
                ('notes', models.CharField(max_length=600, null=True)),
                ('DignityPlan', models.SmallIntegerField(null=True)),
                ('Contract', models.CharField(max_length=125, null=True)),
                ('e_email', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
