# Generated by Django 5.0.4 on 2024-05-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0007_pesevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='eventdate',
            field=models.DateTimeField(),
        ),
    ]
