# Generated by Django 5.0.4 on 2024-05-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0008_alter_pesevents_eventdate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pesevents',
            table='PesEvents',
        ),
    ]
