# Generated by Django 5.0.4 on 2024-05-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0009_alter_pesevents_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='eventdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
