# Generated by Django 5.0.4 on 2024-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0009_alter_pesevents_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='FaxDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='ReportDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_DOD',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_disp_Postal',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_dispdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='eventdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
