# Generated by Django 5.0.4 on 2024-05-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0010_alter_pesevents_eventdate'),
        ('pes', '0010_alter_pesevents_faxdate_alter_pesevents_reportdate_and_more'),
    ]

    operations = [
    ]
