# Generated by Django 5.0.4 on 2024-05-02 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0010_alter_pesevents_faxdate_alter_pesevents_reportdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='eventdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
