# Generated by Django 5.0.4 on 2024-05-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0012_pesexecutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='d_disp_Name',
            field=models.CharField(blank=True, max_length=275, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_dispdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
