# Generated by Django 5.0.4 on 2024-05-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0011_merge_20240502_0722'),
        ('pes', '0012_pesexecutor'),
    ]

    operations = [
    ]
