# Generated by Django 5.0.4 on 2024-05-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0013_alter_pesevents_d_disp_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='d_dispdate',
            field=models.DateField(null=True),
        ),
    ]
