# Generated by Django 5.0.4 on 2024-05-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0014_alter_pesevents_d_dispdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='FaxDate',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='ReportDate',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_DOB',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_DOD',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_dispdate',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
