# Generated by Django 5.0.4 on 2024-05-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0013_merge_0011_merge_20240502_0722_0012_pesexecutor'),
        ('pes', '0015_alter_pesevents_faxdate_alter_pesevents_reportdate_and_more'),
    ]

    operations = [
    ]
