# Generated by Django 5.0.4 on 2024-05-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0016_alter_pesevents_contract_alter_pesevents_dignityplan_and_more'),
        ('pes', '0016_merge_20240524_0952'),
    ]

    operations = [
    ]
