# Generated by Django 5.0.4 on 2024-06-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0017_alter_pesevents_d_postal_alter_pesevents_e_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='eventdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
