# Generated by Django 5.0.4 on 2024-05-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0017_alter_pesevents_d_postal_alter_pesevents_e_postal'),
        ('pes', '0017_merge_20240530_0309'),
    ]

    operations = [
    ]
