# Generated by Django 5.0.4 on 2024-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0018_alter_pesevents_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='d_AreaCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_exchange',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
