# Generated by Django 5.0.4 on 2024-06-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0018_alter_pesevents_eventdate'),
        ('pes', '0018_merge_20240530_0710'),
    ]

    operations = [
    ]
