# Generated by Django 5.0.4 on 2024-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0019_alter_pesevents_d_areacode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='ReportDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='eventdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
