# Generated by Django 5.0.4 on 2024-06-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0019_alter_pesevents_d_areacode_and_more'),
        ('pes', '0019_merge_20240602_0648'),
    ]

    operations = [
    ]
