# Generated by Django 5.0.4 on 2024-06-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0020_alter_pesevents_reportdate_alter_pesevents_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesevents',
            name='UpdateID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
