# Generated by Django 5.0.4 on 2024-06-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0020_merge_20240602_0831'),
        ('pes', '0021_pesevents_updateid'),
    ]

    operations = [
    ]
