# Generated by Django 5.0.4 on 2024-06-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0021_pesevents_updateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='FaxDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
