# Generated by Django 5.0.4 on 2024-06-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0022_alter_pesevents_faxdate'),
        ('pes', '0022_merge_20240612_1016'),
    ]

    operations = [
    ]
