# Generated by Django 5.0.4 on 2024-06-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0022_alter_pesevents_faxdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesevents',
            name='Created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pesevents',
            name='Modify_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='eventdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
