# Generated by Django 5.0.4 on 2024-06-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0023_merge_20240612_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='eventdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
