# Generated by Django 5.0.4 on 2024-06-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0023_pesevents_created_date_pesevents_modify_date_and_more'),
        ('pes', '0024_alter_pesevents_eventdate'),
    ]

    operations = [
    ]
