# Generated by Django 5.0.6 on 2024-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0025_merge_20240613_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('locationid', models.AutoField(db_column='LocationID', primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, db_column='Status', null=True)),
                ('locationname', models.CharField(db_column='LocationName', max_length=125)),
                ('parentcompany', models.CharField(blank=True, db_column='ParentCompany', max_length=125, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('prov', models.CharField(blank=True, db_column='Prov', max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=12, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=125, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=50, null=True)),
                ('adminemail', models.CharField(blank=True, db_column='AdminEmail', max_length=128, null=True)),
                ('customurl', models.CharField(blank=True, db_column='CustomURL', max_length=255, null=True)),
                ('managementemail', models.CharField(blank=True, db_column='ManagementEmail', max_length=125, null=True)),
                ('billingcode', models.CharField(blank=True, db_column='BillingCode', max_length=50, null=True)),
                ('oldlocation', models.CharField(blank=True, db_column='OldLocation', max_length=50, null=True)),
                ('servicename', models.CharField(blank=True, db_column='ServiceName', max_length=255, null=True)),
                ('billingnotes', models.CharField(blank=True, db_column='BillingNotes', max_length=255, null=True)),
                ('billingemail', models.CharField(blank=True, db_column='BillingEmail', max_length=125, null=True)),
                ('miscnotes', models.CharField(blank=True, db_column='MiscNotes', max_length=255, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=125, null=True)),
                ('logosmall', models.BinaryField(blank=True, db_column='LogoSmall', max_length='max', null=True)),
                ('logolarge', models.BinaryField(blank=True, db_column='LogoLarge', max_length='max', null=True)),
                ('dateadded', models.DateTimeField(blank=True, db_column='DateAdded', null=True)),
            ],
            options={
                'db_table': 'Locations',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_DOD',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='d_dispdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
