# Generated by Django 5.0.4 on 2024-06-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0026_locations_alter_pesevents_d_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSPs',
            fields=[
                ('fspid', models.AutoField(db_column='FSPID', primary_key=True, serialize=False)),
                ('status', models.IntegerField(db_column='Status')),
                ('f_first', models.CharField(blank=True, max_length=75, null=True)),
                ('f_last', models.CharField(blank=True, max_length=125, null=True)),
                ('fspphone', models.CharField(blank=True, db_column='FSPPhone', max_length=32, null=True)),
                ('fspemail', models.CharField(blank=True, db_column='FSPEmail', max_length=128, null=True)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('jobtitle', models.CharField(blank=True, db_column='JobTitle', max_length=50, null=True)),
                ('oldid', models.IntegerField(blank=True, db_column='OldID', null=True)),
                ('fspdateadded', models.DateTimeField(blank=True, db_column='FSPDateAdded', null=True)),
                ('lastaccessed', models.DateTimeField(blank=True, db_column='LastAccessed', null=True)),
                ('logincount', models.DecimalField(blank=True, db_column='LoginCount', decimal_places=0, max_digits=18, null=True)),
                ('languageid', models.CharField(blank=True, db_column='LanguageID', max_length=2, null=True)),
                ('routingid', models.CharField(blank=True, db_column='RoutingID', max_length=50, null=True)),
            ],
            options={
                'db_table': 'FSPs',
                'managed': False,
            },
        ),
    ]
