# Generated by Django 5.0.4 on 2024-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0029_aftercare_aftercare360_country_modifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesevents',
            name='e_AreaCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='e_exchange',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesevents',
            name='e_phone_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
