from django.urls import path,re_path
from . import views
urlpatterns = [
    path('register/', views.RegisterView.as_view()),
    path('login/', views.LoginView.as_view()),
    path('adminlogin/', views.AdminLoginView.as_view()), 
    path('test_token/', views.test_token, name='test_token'), 
    path('user/', views.UserView.as_view()),
    path('logout/', views.LogoutView.as_view()),
    path('password/reset/', views.AddRandomCode.as_view()),
    path('password/check_code/', views.CheckCodeExist.as_view()),
    path('password/change_password/', views.ChangePassword.as_view()),
    path('events/',views.events_list, name='events-list'),
    path('search_pes_events/', views.search_pes_events, name='search_pes_events'),
    # path('tables_data/',get_data_from_tables, name='events-list'),
    path('events_list/',views.event_list_today, name='events-list'),
    path('create_events/',views.events_create, name='events-create'),
    path('events/<int:pk>/', views.EventsRetrieveUpdateDeleteView.as_view(), name='events-retrieve-update-delete'),
    path('event_modify/', views.event_modify, name='event-modify-update'),
    path('event_admin/', views.event_admin, name='event-admin-update'),
    path('after_care/<int:location_id>/', views.after_care_page, name='after_care_page'),
    path('after_care_page360/<int:location_id>/', views.after_care_page360, name='after_care_page'),
    path('modifier_page/<int:location_id>/', views.modifier_page, name='modifier_page'),
    path('get_full_dump/<int:event_id>/', views.get_full_dump, name='get_full_dump'),
    re_path(r'^updates/?$', views.get_all_updates, name='get_all_updates'),
    path('getUpdate/<int:event_id>/', views.get_update_by_event_id, name='get-update-by-event-id'),
    path('events_list_2/', views.event_list_yesterday, name='event-list-2'),
    path('doa_tomorrow_report/', views.event_list_tomorrow, name='doa_tomorrow_report'),
    path('three_days_ago_report/', views.three_days_ago_report, name='three_days_ago_report'),
    path('events_list_30/', views.event_list_30, name='event-list-30'),
    path('events_list_hold/', views.event_list_hold, name='event-list-hold'),
    path('report/<int:days_ago>/', views.event_list_reports, name='event-list-report'),
    path('fsp/', views.get_fsp, name='get_fsp'),
    path('locations/', views.LocationListCreate.as_view(), name='locations-list'),
    path('download_locations/', views.AdminReportLocations.as_view(), name='download-locations'),
    path('fsps_list/', views.FSPsListCreate.as_view(), name='fsps-list'),
    path('download_user/', views.AdminReportFSPs.as_view(), name='download-user'),
    path('fsps_list1/', views.perform_create, name='fsps-list'),
    path('getlocations/', views.getlocations, name='getlocations'),
    path('countries/', views.countries, name='countries'),
    path('get_data_from_location/<str:locationname>/', views.get_data_from_location, name='get_data_from_location'),
    path('locations/<int:pk>/', views.LocationDetailAPIView.as_view(), name='location-detail'),
    path('fsps_detail/<int:pk>/', views.FSPsDetailAPIView.as_view(), name='fsps-detail'),
    path('get_fsps_by_locationid/<int:locationid>/', views.FSPsByLocationIDView.as_view(), name='get_fsps_by_locationid'),

    #re_path(r'^get_full_dump/<int:event_id>/?$', get_full_dump, name='get_full_dump'),
    # path('pesevents/?', pes_event_search_api_view, name='pesevent-search'),
    # re_path(r'^PesEventsList/?$', views.PesEventsList.as_view(), name='PesEventsList'),
    # Uncomment the lines below if you want to apply the re_path for specific URLs
    # re_path(r'^filterFSPID/(?P<fspid>\d+)/?$', views.filter_pes_events_by_fspid, name='get_fspid_record'),
    # re_path(r'^create_record/?$', views.CreateRecordAPIView.as_view()),
    re_path(r'^ClientAgreement2024/?$', views.PdfDownload.as_view(), name='pdf-download'),
    re_path(r'^OASNotification/?$', views.OASNotification.as_view(), name='pdf-OASNotification'),
    re_path(r'^OASNotificationEA/?$', views.OASNotificationEA.as_view(), name='pdf-OASNotificationEA'),
    re_path(r'^CPPSource2024/?$', views.CPPSource2024.as_view(), name='pdf-CPPSource2024'),
    re_path(r'^CPPSurvivor/?$', views.CPPSurvivor.as_view(), name='pdf-CPPSurvivor'),
    re_path(r'^SecondNewCPPSurvivor/?$', views.SecondNewCPPSurvivor.as_view(), name='pdf-SecondNewCPPSurvivor'),
    re_path(r'^CPPSurvivor2a/?$', views.CPPSurvivor2a.as_view(), name='pdf-CPPSurvivor2a'),
    re_path(r'^CRAForm/?$', views.CRAForm.as_view(), name='pdf-CRAForm'),
    re_path(r'^CRArep/?$', views.CRArep.as_view(), name='pdf-CRArep'),
    re_path(r'^PODmargins/?$', views.PODmargins.as_view(), name='pdf-PODmargins'),
    re_path(r'^CPPStudent/?$', views.CPPStudent.as_view(), name='pdf-CPPStudent'),
    re_path(r'^PODSource/?$', views.PODSource.as_view(), name='pdf-PODSource'),
    re_path(r'^PrivacyPOD/?$', views.PrivacyPOD.as_view(), name='pdf-PrivacyPOD'),
    re_path(r'^FDSSsource/?$', views.FDSSsource.as_view(), name='pdf-FDSSsource'),
    re_path(r'^PrivacyFDSS/?$', views.PrivacyFDSS.as_view(), name='pdf-PrivacyFDSS'),
    re_path(r'^StatementofServices2022/?$', views.StatementofServices2022.as_view(), name='pdf-StatementofServices2022'),
    re_path(r'^BCCIS/?$', views.BCCIS.as_view(), name='pdf-BCCIS'),
    re_path(r'^DeclarationLegalMarriage/?$', views.DeclarationLegalMarriage.as_view(), name='pdf-DeclarationLegalMarriage'),
    re_path(r'^CommonLawUnion/?$', views.CommonLawUnion.as_view(), name='pdf-CommonLawUnion'),
    re_path(r'^RSKANE/?$', views.RSKANE.as_view(), name='pdf-RSKANE'),
    re_path(r'^EAClientAgreement/?$', views.AOAFORM.as_view(), name='pdf-AOAFORM'),
    re_path(r'^EABlankCA/?$', views.EABlankCA.as_view(), name='pdf-EABlankCA'),
    re_path(r'^fspStatementofServices/?$', views.fspStatementofServices.as_view(), name='pdf-fspStatementofServices'),
    re_path(r'^ClientLetters/?$', views.ClientLetters.as_view(), name='pdf-ClientLetters'),
    re_path(r'^AftercareTrackingSheet/?$', views.AftercareTrackingSheet.as_view(), name='pdf-AftercareTrackingSheet'),
    re_path(r'^EAWorkbook2024b/?$', views.EAWorkbook2024b.as_view(), name='pdf-EAWorkbook2024b'),
    re_path(r'^ClientData/?$', views.ClientData.as_view(), name='pdf-ClientData'),
    re_path(r'^BCClientData/?$', views.BCClientData.as_view(), name='pdf-BCClientData'),
    re_path(r'^EAWebsiteLetter/?$', views.EAWebsiteLetter.as_view(), name='pdf-EAWebsiteLetter'),
    re_path(r'^ClientAgreementFR/?$', views.ClientAgreementFR.as_view(), name='pdf-ClientAgreementFR'),
    re_path(r'^StatementofServiceFR/?$', views.StatementofServiceFR.as_view(), name='pdf-StatementofServiceFR'),
    re_path(r'^FDSDsource/?$', views.FDSDsource.as_view(), name='pdf-FDSDsource'),
    re_path(r'^PrivacyFDSD/?$', views.PrivacyFDSD.as_view(), name='pdf-PrivacyFDSD'),
    re_path(r'^FDSDnoSIN/?$', views.FDSDnoSIN.as_view(), name='pdf-FDSDnoSIN'),
    re_path(r'^QPPfr/?$', views.QPPfr.as_view(), name='pdf-QPPfr'),
    re_path(r'^QPPSource/?$', views.QPPSource.as_view(), name='pdf-QPPSource'),
    re_path(r'^CPP_Source_FR/?$', views.CPP_Source_FR.as_view(), name='pdf-CPP_Source_FR'),
    re_path(r'^CRASource_FR/?$', views.CRASource_FR.as_view(), name='pdf-CRASource_FR'),
    re_path(r'^SurvivorSource_FR/?$', views.SurvivorSource_FR.as_view(), name='pdf-SurvivorSource_FR'),
    re_path(r'^OASNotif_FR/?$', views.OASNotif_FR.as_view(), name='pdf-OASNotif_FR'),
    re_path(r'^EAAftercareTrackingSheet/?$', views.EAAftercareTrackingSheet.as_view(), name='pdf-EAAftercareTrackingSheet'),
    re_path(r'^ASBForm/?$', views.ASBForm.as_view(), name='pdf-ASBForm'),
    re_path(r'^OASapplication/?$', views.NewCPPSurvivor.as_view(), name='pdf-NewCPPSurvivor'),
]

